### PR TITLE
docker image with SRT support

### PR DESCRIPTION
**Pull request by dimahwang88**
- opencv_with_srt contains Dockerfile for opencv-python with SRT support
- stitching_base Dockerfile contains changes related to upgrading ffmpeg to 4.4

### CODE REVIEW

**Review by nalssing — COMMENTED** [review]
- How new `bepro/opencv:23.05` is used in stitching program?
- If is used as public image, script `stitching_base/build.sh` should be copied to `opencv_with_srt` and tag name inside script needs to be changed.

**Comment by dimahwang88** [comment]
@nalssing opencv:23.05 isn't intended for use in video pipeline. This image is necessary as the base image of live tracking machine. The difference between opencv in video pipeline and this image is SRT support. For this reason, I've placed opencv:23.05's Dockerfile into a separate directory. 
Do you think this image still needs to be referenced somewhere?

**Comment by nalssing** [comment]
Oh I thought that it was for video pipeline. Then current directory and script structure just looks good.

**Comment by nalssing** [comment]
There is a change in stitching_base, bumping `name_tag` up in `stitching_base/build.sh` seems to be a good idea for deployment. Later stitching builder should update it also.

**Comment by dimahwang88** [comment]
changed tag to stitching_base:23.06 (following year.month convention)

**Review by alexisrozhkov — APPROVED** [review]
Looks good to me!

**Review by nalssing — APPROVED** [review]
Looks good to me, too.

**Pull request merged**
