### PR TITLE
Toml build

### PR DESCRIPTION
**Pull request by jahwanoh**
adding toml installation script.
so that it removes the internet constraints in video pipeline cmake build.

### CODE REVIEW

**Comment by jahwanoh** [comment]
I will test more before merge.

**Review by nalssing — APPROVED** [review]
It looks okay to me. I understand that `FetchContent_MakeAvailable` detects library is available first and then fetches content otherwise, right?

**Comment by jahwanoh** [comment]
@nalssing 
this is the related PR
https://github.com/bepro-company/bepro-video-stitching/pull/695

**Review by felibol — APPROVED** [review]

**Comment by nalssing** [comment]
Is it held or waiting other approval?

**Comment by jahwanoh** [comment]
I will merge it today! @nalssing

**Pull request merged**
